"""first install of schema

Revision ID: 431ef6cc1203
Revises: 
Create Date: 2023-05-22 08:38:57.899110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431ef6cc1203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_abbrev'), 'vendors', ['abbrev'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_reference', sa.String(), nullable=False),
    sa.Column('id_expiry_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_on_order', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id_expiry_date'), 'products', ['id_expiry_date'], unique=False)
    op.create_index(op.f('ix_products_id_reference'), 'products', ['id_reference'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('vendor_abbrev', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_abbrev'], ['vendors.abbrev'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_index(op.f('ix_products_id_reference'), table_name='products')
    op.drop_index(op.f('ix_products_id_expiry_date'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_vendors_abbrev'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
