"""added purchase date to Purchase object

Revision ID: 90009b7db612
Revises: f11cb8652ad1
Create Date: 2023-05-22 09:39:36.087504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90009b7db612'
down_revision = 'f11cb8652ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'date')
    # ### end Alembic commands ###
