"""updated type for expiry_date to String

Revision ID: 96986242595e
Revises: e1bcee992a83
Create Date: 2023-05-23 08:36:30.618458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96986242595e'
down_revision = 'e1bcee992a83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
