"""undo unique constraint

Revision ID: ac52b99d2e7d
Revises: 90009b7db612
Create Date: 2023-05-22 14:05:50.072314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac52b99d2e7d'
down_revision = '90009b7db612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
