"""added ref-id-expiry column, revised

Revision ID: e1bcee992a83
Revises: 2453381c5926
Create Date: 2023-05-22 16:07:34.934234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1bcee992a83"
down_revision = "2453381c5926"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ref_id_expiry_date", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("ref_id_expiry_date")

    # ### end Alembic commands ###
