"""removed autoincrement, need to add IDs manually

Revision ID: f11cb8652ad1
Revises: 431ef6cc1203
Create Date: 2023-05-22 09:23:14.316515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11cb8652ad1'
down_revision = '431ef6cc1203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
